### PR TITLE
Customized settings cells. #781

### LINKED ISSUE #781: Customize settings cells.
Labels are broken and not aligned.
74523164-e2255f00-4f1c-11ea-93f3-4d4687823348

### PR DESCRIPTION
**Pull request by shahenAnt**
Fix #781 

## Checklist:

- [ ] My squashed commit messages follows the [7 golden rules](https://chris.beams.io/posts/git-commit/)
- [ ] I updated or created necessary unit tests
- [ ] I've tested my changes in Dark Mode, iPad, iOS <= 12, Landscape and in German

### CODE REVIEW

File: Client/Frontend/Settings/SettingsTableViewController.swift [hunk 1]
```diff
@@ -566,10 +556,14 @@ class SettingsTableViewController: ThemedTableViewController {
     override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
         let section = settings[indexPath.section]
         if let setting = section[indexPath.row] {
-            let cell = ThemedTableViewCell(style: setting.style, reuseIdentifier: nil)
-            setting.onConfigureCell(cell)
-            cell.backgroundColor = Theme.tableView.rowBackground
-            return cell
+            let identifier = Identifier + "_\(setting.style.rawValue)"
+            var cell = tableView.dequeueReusableCell(withIdentifier: identifier) as? ThemedTableViewCell
```
Comment (chrmod) [inline Client/Frontend/Settings/SettingsTableViewController.swift]: :+1:

File: Client/Frontend/Settings/SettingsTableViewController.swift [hunk 2]
```diff
@@ -566,10 +556,14 @@ class SettingsTableViewController: ThemedTableViewController {
...
+            if cell == nil {
```
Comment (chrmod) [inline Client/Frontend/Settings/SettingsTableViewController.swift]: how about:
```
             let cell = tableView.dequeueReusableCell(withIdentifier: identifier) as? ThemedTableViewCell ?? ThemedTableViewCell(style: setting.style, reuseIdentifier: identifier)
```

Comment (chrmod) [reply Client/Frontend/Settings/SettingsTableViewController.swift]: So there `!` wont be required later on.

File: Client/Frontend/Theme/ThemedWidgets.swift [hunk 3]
```diff
@@ -3,12 +3,59 @@
...
 
+private struct ThemedTableViewCellUX {
+    static let CellSideOffset: CGFloat = 20.0
+    static let TitleLabelOffset: CGFloat = 10.0
+    static let CellTopBottomOffset: CGFloat = 11.0
+    static let IconSize: CGFloat = 24.0
+    static let CornerRadius: CGFloat = 3.0
+}
+
 class ThemedTableViewCell: UITableViewCell, Themeable {
```
Comment (chrmod) [inline Client/Frontend/Theme/ThemedWidgets.swift]: I would probably move this one to it's own file
