### PR TITLE
Fixed Search background problems #775

### LINKED ISSUE #775: Search background problems
- light background has navigation bar visible on the bottom
- rotate in landscape ( now its stretched )

### PR DESCRIPTION
**Pull request by shahenAnt**
Fix #775 

## Checklist:

- [ ] My squashed commit messages follows the [7 golden rules](https://chris.beams.io/posts/git-commit/)
- [ ] I updated or created necessary unit tests
- [ ] I've tested my changes in Dark Mode, iPad, iOS <= 12, Landscape and in German

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -169,6 +182,12 @@ class BrowserViewController: UIViewController {
         dismissVisibleMenus()
 
         coordinator.animate(alongsideTransition: { context in
+            let portrateImage = UIImage(named: "searchBackgroundImage")
```
Comment (chrmod) [inline Client/Frontend/Browser/BrowserViewController.swift]: How about we move  this block into `searchBackgroundImageView` , looks like it repeats itself

Comment (chrmod) [reply Client/Frontend/Browser/BrowserViewController.swift]: Oh, It cannot be moved as it has to be checked everytime. 

How about putting it in a function?
