### PR TITLE
Fixed User Agent string issues #656

### LINKED ISSUE #656: User Agent string issues
Our customizations of the User Agent string seem to bring multiple issues:
* qwant.com does not load due to User Agent string 
* On iPad twitter.com loads in mobile version and when requesting the mobile version it loads the desktop - this is likely caused by https://github.com/cliqz/user-agent-ios/commit/97e096ff00b2af32f77e3c904fb60acaaf0cec88#diff-d4885e86bd962ac773c57e9396a92c02L137

Looking at all those issues it make me think that we should either mask our browser as Firefox for iOS or even as Safari. If youtube.com fullscreen mode will be fixed by using default user agent string then I would suggest to go for it.

### PR DESCRIPTION
**Pull request by shahenAnt**
Fix #656 

## Implementation details
Cherry picked Firefox latest version of UserAgent.
1. qwant.com loading properly
2. twitter.com works like Firefox app.(Think need to do more investigation)
3. youtube.com fullscreen doens't work still. (The Firefox/Google/Yandex also doesn't suppurt fullscreen).

## Checklist:

- [ ] My squashed commit messages follows the [7 golden rules](https://chris.beams.io/posts/git-commit/)
- [ ] I updated or created necessary unit tests
- [ ] I've tested my changes in Dark Mode, iPad, iOS <= 12, Landscape and in German

### CODE REVIEW

File: Shared/UserAgent.swift [hunk 1]
```diff
@@ -28,41 +28,110 @@ open class UserAgent {
...
+}
+
+public enum UserAgentPlatform {
+    case Desktop
+    case Mobile
+}
+
+public struct CustomUserAgentConstant {
+    private static let defaultMobileUA = UserAgentBuilder.defaultMobileUserAgent().userAgent()
+    private static let customDesktopUA = UserAgentBuilder.defaultDesktopUserAgent().clone(extensions: "Version/\(AppInfo.appVersion) \(UserAgent.uaBitSafari)")
```
Comment (chrmod) [inline Shared/UserAgent.swift]: This should probably use fixed Firefox version (21)

Comment (shahenAnt) [reply Shared/UserAgent.swift]: Fixed.
